<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tour Dates</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>Tour Dates</h1>
        <p><a href="home">Home</a></p>
        <p><a href="bio">Bio</a></p>
        <p><a href="sounds">Sounds</a></p>
        <p><a href="td">Tour Dates</a></p>
        <p><a href="contact">Contact</a></p>
        <main>
            <h3>Tour Dates</h3>
            <ul>
                <li>Brooklyn, New York:10/7/22</li>
                <li>Los Angeles, California:10/14/22</li>
            </ul>
        </main>
    </body>
    
</html>